version: "3.8"
services:
  db-dev:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbtest
    ports: 
      - '5433:5432'
    volumes:
      - bgapi-db:/var/lib/postgresql/data

  db-test:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbtest
    ports: 
      - '5434:5432'
    volumes:
      - bgapi-db-test:/var/lib/postgresql/data

  bgapi:
    build:  
      context: .
      dockerfile: Dockerfile
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: dbtest
      DB_HOST: db-dev
      DB_TEST_HOST: db-test
    depends_on:
      - db-dev
      - db-test
    ports:
      - '3000:3000'
        
volumes:
  bgapi-db:
  bgapi-db-test: